apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkusjava-gh-quay-tekton-test
  janus-idp.io/tekton: quarkusjava-gh-quay-tekton-test
  backstage.io/kubernetes-id: quarkusjava-gh-quay-tekton-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkusjava-gh-quay-tekton-test
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
