apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkusjava-gh-quay-tekton-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkusjava-gh-quay-tekton-test 
  name: quarkusjava-gh-quay-tekton-test
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkusjava-gh-quay-tekton-test
    weight: 100 
